### ISSUE TITLE
Login via Google Hangs

### ISSUE THREAD

**Issue by cgijb** [search5/Evernote-for-Linux#1]
### Issue Summary

Google authentication hangs.

### Steps to Reproduce

1. Open the app
2. When the login screen appears click the Google icon
3. Browser (in this case, [Brave](https://brave.com)) opens and able to select Google account
4. Prompted to close tab (so do that)
5. Go back to Evernote window

#### Actual Results

Application sits with "Signing in..." message showing.

#### Expected Results

"Signing in..." is automatically dismissed and taken to the full UI.

### System Information

```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

### Other Notes

- I am able to log in to the Evernote web via the Google login, so it's not the account
- Account was set up via Google SSO, so using username/password is not an option here

### Screenshots

![EvernoteBrowser](https://user-images.githubusercontent.com/80909553/116267233-398ea400-a74a-11eb-8555-da20811a8aa0.png)

![EvernoteClient](https://user-images.githubusercontent.com/80909553/116267248-3d222b00-a74a-11eb-803e-4b49775633e1.png)

**Comment by search5** [comment]
@cgijb Sorry.

Evernote distributed in this repository is not officially distributed by Evernote, so we cannot provide any support.

However, thank you for leaving the issue.
