### ISSUE TITLE
Evernote client 10.60.4 says it is not supported

### ISSUE THREAD

**Issue by aborovyi** [search5/Evernote-for-Linux#11]
I was logged off from the Evernote client, and during my re-login I'm getting message "Client not supported, please upgrade".

Evernote's verison: 10.60.4:
```
$ LANG=C apt-cache show evernote-client
Package: evernote-client
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 521300
Maintainer: Evernote Corporation <en-eng-core-zone@evernote.com>
Architecture: amd64
Version: 10.60.4-20230803182206
Depends: libgtk-3-0, libnotify4, libnss3, libxtst6, xdg-utils, libatspi2.0-0, libdrm2, libgbm1, libxcb-dri3-0, kde-cli-tools | kde-runtime | trash-cli | libglib2.0-bin | gvfs-bin
Recommends: pulseaudio | libasound2
Suggests: gir1.2-gnomekeyring-1.0, libgnome-keyring0, lsb-release
Description: evernote-client
 evernote-client
Description-md5: 
Homepage: https://evernote.com/
```

Console log is attached
[evernote_client_console.log](https://github.com/search5/Evernote-for-Linux/files/14756254/evernote_client_console.log)

**Comment by wokawoka** [comment]
I guess we are all experiencing this
See also #10 
There's nothing to do unless someone who is capable starts to build new releases in the same way @search5 was previously doing

**Comment by search5** [comment]
@aborovyi @wokawoka When Vendingspoon acquired Evernote, they removed all Linux-specific support code that was included in the binaries for Windows.
As a result, it is no longer possible to repackage for Linux. We apologize that we are unable to support the project any longer.
