### ISSUE TITLE
Left Notes panel in dark has poor font rendering

### ISSUE THREAD

**Issue by prashantjain25** [search5/Evernote-for-Linux#3]
Expected behaviour:-
- webkit-font-smoothing: antialiased;
- text-rendering: geometricPrecision;
- text-shadow: 1px 1px 2px grey;
- font-family: Arial

**Comment by search5** [comment]
I'm sorry, the program distributed in this repository is not officially distributed by Evernote Corporation, but simply repackaged and provided, so it's difficult to provide any support.
