### ISSUE TITLE
Problem with images in notes

### ISSUE THREAD

**Issue by ValentinPostindustria** [search5/Evernote-for-Linux#6]
The app doesn't display any images. Does every Linux user have such a problem? Or it's my mistake? 
![изображение](https://user-images.githubusercontent.com/72038591/175821217-8c03cdfe-035d-4da2-bc54-cf61069813c8.png)

**Comment by search5** [comment]
Updated the new Evernote release. Please use it in the new version.

**Comment by ValentinPostindustria** [comment]
I updated Evernote. And unfortunately, I still get this error on my Kubuntu 22.04. 
I know that Evernote is not your app, but maybe you can help to find the reason. 
My app shows such logs:
```
WARN: electron.main/6075 /usr/lib/evernote-client/resources/app/node_modules/en-ts-utils/src/logger.ts:202 
in warn: conduit-electron-worker 
[["Failed to download attachment 869c5020-198f-a610-c354-2e7636e8475e for note d9b47193-ef1f-5157-9194-af71b55b067e ",
"Error: Error invoking remote method 'conduit-electron-content-fetch-ipc': 
Error: AuthToken:User:144525444 does not exist in secure storage, the user is unauthenticated
at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73:529)\n    
at async h.fetchResource (app://evernote/boronConduitWorker/586-297eb28aa4df345f27f2.js:40:134204)"]]
```
