### ISSUE TITLE
Regular updates

### ISSUE THREAD

**Issue by llabusch93** [search5/Evernote-for-Linux#9]
Hello,

Thank you for the fantastic work on the Evernote client for Linux. Your efforts are particularly appreciated following Evernote's announcement of discontinuing updates for the Linux Beta client.

Could you please inform me about the frequency of updates for this client? Is the process automated, with a service that monitors, builds, and uploads updates, or is it managed manually?

Additionally, I'd like to offer my support. Is there anything I can do to assist you in this project?

Best regards,
Laurence

**Comment by arturolinares** [comment]
It would be great if it was done automatically, maybe even using GitHub actions, but I have been unable to build the client manually following the instructions in the readme. It appears that scripts changed after the instructions were written.

**Comment by search5** [comment]
When Vendingspoon acquired Evernote, they removed all Linux-specific support code that was included in the binaries for Windows.
As a result, it is no longer possible to repackage for Linux. We apologize that we are unable to support the project any longer.

**Comment by search5** [comment]
@llabusch93 @arturolinares

**Comment by llabusch93** [comment]
That is really sad news, but it is what it is... Hopefully they will target Linux again, after they are done with all the stabilizing where they already did very very very well.

I mean it's just fu**** Electron... It's really not that hard to port and maintain it. Especially not for such apparently good developers as at BS.
